version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-credentials/docker_registry/url

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r aws-devops-zero-to-hero-main/day-14/simple-python-app/requirements.txt

  build:
    commands:
      - echo "Running tests..."
      - cd aws-devops-zero-to-hero-main/day-14/simple-python-app/
      - echo "Building Docker image..."
      
      # Docker login
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      
      # Build and tag Docker image
      - docker build -t "karthikpilla/simple-python-flask-app:latest" .
      
      # Push Docker image to the repository
      - docker push "$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'
  base-directory: aws-devops-zero-to-hero-main/day-14/simple-python-app
